---
title: "R Notebook"
output: html_notebook
---
```{r}
library(RMySQL)

db_user <- 'dbadmin'
db_password <- 'dos8JINT.kras8jaun'
db_name <- 'SandboxDB'
db_host <- 'cs5200-dbs.ctuc7sl6qeau.us-east-2.rds.amazonaws.com' # AWS Host
db_port <- 3306

mydb <- dbConnect(MySQL(), dbname = db_name, host = db_host, port = db_port,
                  user = db_user, password = db_password)
```

```{sql connection=mydb}
SELECT BirdStrike.birdstrike_id, Aircraft.aircraft_type, Airport.airport_name
       , BirdStrike.altitude_bin, Aircraft.aircraft_name
       , BirdStrike.number_struck_est, BirdStrike.impact_to_flight
       , Flight.flight_date, BirdStrike.indicated_damage
       , Aircraft.number_engines, AirlineOperator.airline_name
       , State.state, BirdStrike.phase_of_flight, Precipitation.precip_name
       , BirdStrike.wildlife_remains_smithsonian, Note.note
       , BirdStrike.wildlife_size, BirdStrike.sky_conditions
       , Wildlife.species, BirdStrike.pilot_warned, BirdStrike.total_cost
       , BirdStrike.feet_above_ground, BirdStrike.num_people_injured
       , Aircraft.large_aircraft
FROM BirdStrike
     JOIN Note
     ON BirdStrike.note_id = Note.n_id
     JOIN Wildlife
     ON BirdStrike.wildlife_id = Wildlife.w_id
     JOIN Precipitation
     ON BirdStrike.birdstrike_id = Precipitation.birdstrike_id
     JOIN Flight
     ON BirdStrike.flight_id = Flight.f_id
     JOIN Aircraft
     ON Flight.aircraft_id = Aircraft.a_id
     JOIN Airport
     ON Flight.origin_airport = Airport.a_id
     JOIN State
     ON Airport.State = State.s_id
     JOIN AirlineOperator
     ON Flight.airline_operator = AirlineOperator.ao_id
     ORDER BY birdstrike_id DESC;
```
```{r}
df <- dbGetQuery(mydb, "SELECT BirdStrike.birdstrike_id, Aircraft.aircraft_type, Airport.airport_name
       , BirdStrike.altitude_bin, Aircraft.aircraft_name
       , BirdStrike.number_struck_est, BirdStrike.impact_to_flight
       , Flight.flight_date, BirdStrike.indicated_damage
       , Aircraft.number_engines, AirlineOperator.airline_name
       , State.state, BirdStrike.phase_of_flight, Precipitation.precip_name
       , BirdStrike.wildlife_remains_smithsonian, Note.note
       , BirdStrike.wildlife_size, BirdStrike.sky_conditions
       , Wildlife.species, BirdStrike.pilot_warned, BirdStrike.total_cost
       , BirdStrike.feet_above_ground, BirdStrike.num_people_injured
       , Aircraft.large_aircraft
FROM BirdStrike
     JOIN Note
     ON BirdStrike.note_id = Note.n_id
     JOIN Wildlife
     ON BirdStrike.wildlife_id = Wildlife.w_id
     JOIN Precipitation
     ON BirdStrike.birdstrike_id = Precipitation.birdstrike_id
     JOIN Flight
     ON BirdStrike.flight_id = Flight.f_id
     JOIN Aircraft
     ON Flight.aircraft_id = Aircraft.a_id
     JOIN Airport
     ON Flight.origin_airport = Airport.a_id
     JOIN State
     ON Airport.State = State.s_id
     JOIN AirlineOperator
     ON Flight.airline_operator = AirlineOperator.ao_id
     ORDER BY birdstrike_id DESC;")
write.csv(df, "bird_strike_from_AWS.csv", row.names = FALSE)

```

## Draft stored procedure
```{sql connection=mydb}
DELIMETER // --might not need this delimiter thing
CREATE PROCEDURE Remove_BirdStrike (IN birdstrike_id_to_delete INTEGER)
BEGIN
  DELETE FROM Note WHERE Note.n_id = (SELECT BirdStrike.note_id FROM BirdStrike WHERE BirdStrike.birdstrike_id = birdstrike_id_to_delete)//
  DELETE FROM Flight WHERE Flight.f_id = (SELECT BirdStrike.flight_id FROM BirdStrike WHERE BirdStrike.birdstrike_id = birdstrike_id_to_delete)//
  DELETE FROM BirdStrike WHERE BirdStrike.birdstrike_id = birdstrike_id_to_delete//
  DELETE FROM Precipitation WHERE Precipitation.birdstrike_id = birdstrike_id_to_delete//
DELIMETER;
```


```{r}
dbDisconnect(mydb)
```

